name = "Orbital Odyssey"
author = "tuxcraft"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ced1ba60e07fd26d0a5a49d1cb673d6ee048e185908da9a28c478dce5959beef"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
