name = "Orbital Odyssey"
author = "tuxcraft"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f7b5db69fa0d20b33f4c5e4b2f1633ac9c5c6f9034a556e0b2047cacd5183eb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
